In [1]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as seabornInstance 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics
%matplotlib inline

In [8]:
train = np.loadtxt("Gamma_train.txt",dtype='float',delimiter=',',skiprows=0)

In [9]:
print(train
     )

[[ 4.9646  0.5897  1.    ]
 [ 1.5701  0.0872  1.    ]
 [ 3.3763  0.1963  1.    ]
 ...
 [ 7.2153  3.5391 -1.    ]
 [ 5.2954  5.938  -1.    ]
 [ 3.4157  6.1094 -1.    ]]


In [10]:
print(train[0])

[4.9646 0.5897 1.    ]


In [11]:
print(train.shape)

(2000, 3)


In [14]:
X_train = train[:,:2]

In [15]:
print(X_train)

[[4.9646 0.5897]
 [1.5701 0.0872]
 [3.3763 0.1963]
 ...
 [7.2153 3.5391]
 [5.2954 5.938 ]
 [3.4157 6.1094]]


In [16]:
print(X_train.shape)

(2000, 2)


In [17]:
Y_train = train[:,-1]

In [18]:
print(Y_train)

[ 1.  1.  1. ... -1. -1. -1.]


## for training set size 10

In [21]:
index10 = np.random.randint(0,2000,10)

In [23]:
print(index10)

[1933  451  154 1070 1828  585 1194  597  499 1339]


In [25]:
X_train_10 = X_train[index10] 

In [26]:
print(X_train_10)

[[4.88000e-01 1.94390e+00]
 [2.61000e-02 7.82000e-02]
 [2.48400e-01 3.31000e-02]
 [4.80630e+00 4.44120e+00]
 [7.12280e+00 5.23330e+00]
 [2.07700e-01 3.62000e-01]
 [1.52530e+00 1.22628e+01]
 [2.63280e+00 5.66900e-01]
 [3.57000e-02 7.90000e-03]
 [1.94610e+00 4.09370e+00]]


In [27]:
Y_train_10 = Y_train[index10]

In [28]:
print(Y_train_10)

[-1.  1.  1. -1. -1.  1. -1.  1.  1. -1.]


In [29]:
regressor_10 = LinearRegression()

In [31]:
regressor_10.fit(X_train_10, Y_train_10)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [32]:
test = np.loadtxt("Gamma_test.txt",dtype='float',delimiter=',',skiprows=0)

In [33]:
X_test = test[:,:2]

In [34]:
print(X_test)

[[0.0509 0.0399]
 [0.8071 0.2009]
 [1.1025 0.164 ]
 ...
 [3.5262 0.1474]
 [2.355  4.6955]
 [4.4955 9.8387]]


In [35]:
Y_pred_10 = regressor_10.predict(X_test)

In [36]:
print(Y_pred_10)

[ 7.41068008e-01  6.05447684e-01  5.68997324e-01  7.40981198e-01
  6.83343592e-01  7.01811682e-01  6.10029651e-01  5.51312076e-01
  6.25032595e-01  7.32853233e-01  6.52587965e-01  7.53129581e-01
  7.45562378e-01  5.72727806e-01  6.81732214e-01  4.43909072e-01
  6.02969488e-01  7.04108791e-01  3.11900066e-01  6.37625193e-01
  6.23284373e-01  3.99173850e-01  6.94304896e-01  7.23855063e-01
  6.52419947e-01  6.93547891e-01  6.00014907e-01  6.97504409e-01
  4.48069253e-01  6.44401634e-01  5.21090748e-01  7.45681591e-01
  6.99183182e-01  7.21048752e-01 -4.92458119e-01  7.34696879e-01
  6.47888204e-01  6.88117948e-01  6.21375641e-01  5.94582558e-01
  7.20481622e-01  6.90177434e-01  5.99827280e-01  7.27730450e-01
  6.82636106e-01  6.52872634e-01 -5.19351237e-02  6.76844446e-01
  7.27938483e-01  6.08383018e-01  1.06874832e-01  7.15176749e-01
  7.54760251e-01  7.48682809e-01  7.03440424e-01  7.06688302e-01
  5.73333004e-01  4.46351288e-01  2.97539293e-02  6.91049646e-01
  5.40370458e-01  3.24909

In [37]:
print(Y_pred_10.shape)

(1000,)


In [43]:
Y_pred_10_actual = []
for i in range(len(Y_pred_10)):
    if Y_pred_10[i]>0:
        Y_pred_10_actual.append(1)
    else:
        Y_pred_10_actual.append(-1)

In [44]:
print(Y_pred_10_actual)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [53]:
Y_test = test[:,-1]

In [56]:
final_acc_10 = (Y_pred_10_actual == Y_test).mean()
print("final testing accuracy for train sample size 10: {:.4f}".format(final_acc_10))

final testing accuracy for train sample size 10: 0.8720


## for training set size 50

In [93]:
index50 = np.random.randint(0,2000,50)

In [94]:
X_train_50 = X_train[index50]

In [95]:
Y_train_50 = Y_train[index50]

In [96]:
regressor_50 = LinearRegression()

In [97]:
regressor_50.fit(X_train_50, Y_train_50)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [98]:
Y_pred_50 = regressor_50.predict(X_test)

In [99]:
Y_pred_50_actual = []
for i in range(len(Y_pred_50)):
    if Y_pred_50[i]>0:
        Y_pred_50_actual.append(1)
    else:
        Y_pred_50_actual.append(-1)

In [100]:
print(Y_pred_50_actual)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [101]:
final_acc_50 = (Y_pred_50_actual == Y_test).mean()
print("final testing accuracy for train sample size 50: {:.4f}".format(final_acc_50))

final testing accuracy for train sample size 50: 0.8830


## for training set size 100

In [110]:
index100 = np.random.randint(0,2000,100)
X_train_100 = X_train[index100]
Y_train_100 = Y_train[index100]
regressor_100 = LinearRegression()
regressor_100.fit(X_train_100, Y_train_100)
Y_pred_100 = regressor_100.predict(X_test)
Y_pred_100_actual = []
for i in range(len(Y_pred_100)):
    if Y_pred_100[i]>0:
        Y_pred_100_actual.append(1)
    else:
        Y_pred_100_actual.append(-1)
        
final_acc_100 = (Y_pred_100_actual == Y_test).mean()
print("final testing accuracy for train sample size 100: {:.4f}".format(final_acc_100))

final testing accuracy for train sample size 100: 0.8990


## for training size 500

In [118]:
index500 = np.random.randint(0,2000,500)
X_train_500 = X_train[index500]
Y_train_500 = Y_train[index500]
regressor_500 = LinearRegression()
regressor_500.fit(X_train_500, Y_train_500)
Y_pred_500 = regressor_500.predict(X_test)
Y_pred_500_actual = []
for i in range(len(Y_pred_500)):
    if Y_pred_500[i]>0:
        Y_pred_500_actual.append(1)
    else:
        Y_pred_500_actual.append(-1)
        
final_acc_500 = (Y_pred_500_actual == Y_test).mean()
print("final testing accuracy for train sample size 500: {:.4f}".format(final_acc_500))

final testing accuracy for train sample size 500: 0.9010
