In [9]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as seabornInstance 
from sklearn.model_selection import train_test_split 
from sklearn.linear_model import LinearRegression
from sklearn import metrics
%matplotlib inline

In [4]:
train = np.loadtxt("german.data-numeric")

In [5]:
print(train)

[[ 1.  6.  4. ...  0.  1.  1.]
 [ 2. 48.  2. ...  0.  1.  2.]
 [ 4. 12.  4. ...  1.  0.  1.]
 ...
 [ 4. 12.  2. ...  0.  1.  1.]
 [ 1. 45.  2. ...  0.  1.  2.]
 [ 2. 45.  4. ...  0.  1.  1.]]


In [12]:
X_train_init = train[:,:4]

In [13]:
Y_train_init = train[:,-1]

In [14]:
X_train, X_test, Y_train, Y_test = train_test_split(X_train_init, Y_train_init, test_size=0.2)

## Using Linear Regression

In [15]:
regressor = LinearRegression()

In [16]:
regressor.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [17]:
Y_pred = regressor.predict(X_test)

In [18]:
print(Y_pred)

[1.52684533 1.2893811  1.29341929 0.96984002 1.35759147 1.37947218
 1.10849927 1.3515363  1.32622159 1.4351975  1.47922971 1.52466101
 1.08556845 1.19729642 1.49495679 1.5123913  1.85818173 1.52859278
 1.01828511 1.36767687 1.1575043  1.47671494 1.05825351 1.57873212
 1.18712548 1.38277638 0.96721884 1.18051161 1.48705321 1.64819987
 0.96940315 1.18899601 1.44336041 1.08356822 1.18071119 1.76886468
 1.46068849 1.15184845 1.2254618  1.03799709 1.52466101 1.1309633
 1.57243204 1.29131147 1.04534727 1.72936297 1.17098491 1.54761511
 1.51288907 1.10757233 1.36661915 1.37764044 1.52640846 1.4168117
 1.20308206 1.44585851 1.15409368 1.31253487 1.41219019 0.92707415
 1.32447414 1.47466813 1.17104707 1.0995325  1.35171258 1.10084309
 1.4351975  1.05606919 1.49785943 1.57660101 1.1767263  1.51114162
 1.46199263 1.27060269 1.26001155 1.58670978 1.44012608 1.57878533
 1.38675241 1.50602233 1.30856306 1.59387589 1.09822191 1.30510819
 1.61630883 1.6250461  1.43301318 0.94714649 1.52611805 1.454138

In [19]:
Y_predict_actual = []
for i in range(len(Y_pred)):
    if (abs(1-Y_pred[i])<abs(2-Y_pred[i])):
        Y_predict_actual.append(1)
    else:
        Y_predict_actual.append(2)

In [20]:
final_acc_linear = (Y_predict_actual == Y_test).mean()
print("final testing accuracy: {:.4f}".format(final_acc_linear))

final testing accuracy: 0.6800


## Using logistic regression

In [22]:
from sklearn.linear_model import LogisticRegression

In [23]:
log_regressor = LogisticRegression()

In [24]:
log_regressor.fit(X_train, Y_train)

/opt/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [25]:
Y_pred_log = log_regressor.predict(X_test)

In [26]:
print(Y_pred_log)

[2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 2. 2. 1. 1. 1. 1. 1. 2.
 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 2. 1. 2. 1. 1. 2. 1. 2.
 2. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 2. 2. 1. 2.
 1. 1. 1. 2. 1. 2. 1. 2. 1. 2. 1. 1. 2. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 2. 1. 1. 1. 2. 2. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 2. 1.
 1. 1. 1. 1. 1. 1. 1. 2. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 2. 1. 1. 1. 1. 1. 1. 2.]


In [27]:
final_acc_log = (Y_pred_log == Y_test).mean()
print("final testing accuracy: {:.4f}".format(final_acc_log))

final testing accuracy: 0.6850
